config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from info import views
from notice import views
from rcdb import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notice/', include('notice.urls')),
    path('info/', include('info.urls')),
    path('', include('main.urls')),
    path('rcdb/', include('rcdb.urls')),
]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('', views.index, name='index'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:notice_id>/', views.detail, name='detail'),
]

rcdb/urls.py
from django.urls import path
from . import views

app_name = 'rcdb'

urlpatterns = [
    path('', views.index, name='index'),
]

notice/models.py
from django.db import models
from django.db.models.base import Model

# Create your models here.
class Notice(models.Model):
    subject = models.CharField(max_length=100)
    content = models.TextField()
    create_date = models.DateTimeField()
    
    def __str__(self):
        return self.subject

rcdb/models.py
from django.db import models
from django.db.models.base import Model, ModelStateFieldsCacheDescriptor
from django.db.models.fields import TextField
from django.db.models.fields.reverse_related import ManyToOneRel

# Create your models here.
class rcdb(models.Model):
    Name = models.CharField(max_length=11)
    State = models.CharField(max_length=15)
    City = models.CharField(max_length=15)
    Site = models.CharField(max_length=15)
    Material = models.CharField(max_length=15)
    Weight_g = models.FloatField()
    Laboratory = models.CharField(max_length=15)
    LabID = models.CharField(max_length=15)
    Age_BP = models.IntegerField()
    Error = models.IntegerField()
    Report = models.TextField()

    def __str__(self):
        return self.LabID

info/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'info/index.html')

def candidates(request, name):
    candidate = get_object_or_404(Candidate, name = name)
    return HttpResponse(candidate.name)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'main/index.html')

notice/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from .models import Notice
from django.core.paginator import Paginator

# Create your views here.
def index(request):
    notice_list = Notice.objects.order_by('-create_date')
    context = {'notice_list': notice_list}
    return render(request, 'notice/notice_list.html', context)

def detail(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    context = {'notice' : notice}
    return render(request, 'notice/notice_detail.html', context)

def index(request):
    page = request.GET.get('page', '1')
    notice_list = Notice.objects.order_by('-create_date')
    paginator = Paginator(notice_list, 15)
    page_obj = paginator.get_page(page)
    context = {'notice_list': page_obj}
    return render(request, 'notice/notice_list.html', context)

rcdb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import rcdb
from django.contrib.auth.models import User
from django.core import serializers
import json

def index(request):
    rcdbsDict = []

    for data in rcdb.objects.all():
        tmpdict = {
            "id" : data.id,
            "Name" : data.Name,
            "State" : data.State,
            "City": data.City,
            "Site" : data.Site,
            "Material" : data.Material,
            "Weight_g" : data.Weight_g,
            "Laboratory" : data.Laboratory,
            "LabID" : data.LabID,
            "Age_BP" : data.Age_BP,
            "Error" : data.Error,
            "Report" : data.Report
        }
        rcdbsDict.append(tmpdict)

    rcdbsJson = json.dumps(rcdbsDict, ensure_ascii=False)
    context = {'rcdbsJson' : rcdbsJson}
    return render(request, 'rcdb/index.html', context)

templates/502.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB 502</title>
</head>

<body>
{% include "navbar.html" %}

<div id="error-title">502 Bad Gateway</div>
<div id="error-middle-contents">요청하신 페이지를 찾을 수 없습니다.</div><br>
<div id="error-contents">
    <ul>서버에 문제가 생겼습니다.<br>
        잠시 후 다시 접속해주세요.<br>
    </ul>
</div>

{% include "footer.html" %}
</body>
</html>

templates/footer.html
<div id="footer">
    <div id="footer-contents">
        <footer>
            <a href="mailto:rcdb2021@gmail.com"><img src="https://github.com/ChanToRe/RCDB/blob/master/img/gmail.ico?raw=true"></a>
            <a href="https://github.com/team-RCDB"><img src="https://github.com/ChanToRe/RCDB/blob/master/img/github.ico?raw=true"></a>
            <br>
            <br>
            <span>© 2021. RCDB. All rights reserved</span>
        </footer>
    </div>
</div>

templates/info/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB</title>
</head>

<body>
{% include "navbar.html" %}
<div id="info-contents">
    <center><img src="https://github.com/ChanToRe/RCDB/blob/master/img/Info_IMG.png?raw=true"></center>
    <br>
    <br>
    <h2>Introduction</h2>
    &nbsp;<b>RCDB</b>는 고고학자료 아카이빙에 대해 고민하고, 고고학 연구에 오픈소스 개념을 도입하고자 고민하던 중 시작하게 된 프로젝트입니다.
    &nbsp;고고학 자료는 지난 수 십 년간 종류가 다양해지고 수량이 급격하게 증가하였습니다. 그러므로 점차 개인이 자료를 관리하는 것이 한계에 다다르고 있습니다.
    &nbsp;다양한 고고학 자료 중, 방사성탄소연대측정치를 대상으로 아카이빙을 실시하고 이를 공유하고자 합니다.
    &nbsp;개인이 자료를 분석하는 것보다 여러 사람들이 함께 분석할 때, 더 나은 결과를 얻을 수 있다고 생각합니다.
    &nbsp;궁극적으로는 고고학 연구에 오픈소스 개념이 도입될 수 있는지 고찰해보고자 합니다.
    &nbsp;RCDB에 대한 많은 관심과 이용, 조언 부탁드립니다.
    &nbsp;감사합니다. :)
    <hr>

    <h2>Team</h2>
    <h3>Ju chanhyeok</h3>
    <ul>
        <li>팀장</li>
        <li>숭실대학교 사학과(고고학전공) 석사과정</li>
        <li>Back-End / 총 기획</li>
        <li>Web : <a href="https://chantore.github.io">https://chantore.github.io</a></li>
        <li>E-mail : <a href="&#109;&#97;&#x69;&#x6c;&#x74;&#111;&#x3a;&#119;&#x6e;&#114;&#110;&#114;&#120;&#108;&#x61;&#x40;&#103;&#109;&#97;&#105;&#108;&#x2e;&#99;&#x6f;&#x6d;">&#119;&#x6e;&#114;&#110;&#114;&#120;&#108;&#x61;&#x40;&#103;&#109;&#97;&#105;&#108;&#x2e;&#99;&#x6f;&#x6d;</a><br></li>
    </ul>
    <br>
    <h3>Kim jihun</h3>
    <ul>
        <li>팀원</li>
        <li>한국산업기술대학교 컴퓨터공학부 소프트웨어전공 졸업</li>
        <li>Front-End</li>
        <li>E-mail : <a href="&#x6d;&#97;&#x69;&#108;&#116;&#111;&#58;&#x74;&#111;&#111;&#x6e;&#105;&#118;&#49;&#x32;&#51;&#x40;&#107;&#112;&#x75;&#46;&#97;&#99;&#46;&#x6b;&#114;">&#x74;&#111;&#111;&#x6e;&#105;&#118;&#49;&#x32;&#51;&#x40;&#107;&#112;&#x75;&#46;&#97;&#99;&#46;&#x6b;&#114;</a></li>
    </ul>
    <br>
    <h3>Jung sueun</h3>
    <ul>
        <li>팀원</li>
        <li>홍익대학교 미술사학과 석사과정</li>
        <li>Design</li>
        <li>E-mail : <a href="&#x6d;&#97;&#105;&#x6c;&#x74;&#111;&#58;&#116;&#110;&#100;&#109;&#115;&#x34;&#48;&#50;&#x40;&#x6e;&#x61;&#x76;&#101;&#x72;&#46;&#x63;&#111;&#109;">&#116;&#110;&#100;&#109;&#115;&#x34;&#48;&#50;&#x40;&#x6e;&#x61;&#x76;&#101;&#x72;&#46;&#x63;&#111;&#109;</a></li>
    </ul>
    <hr>

    <h2>Tech Stack</h2>
    <img id="techstack" alt="AWS" src="https://img.shields.io/badge/AWS-%23FF9900.svg?style=for-the-badge&logo=amazon-aws&logoColor=white"/> <img id="techstack" alt="Bootstrap" src="https://img.shields.io/badge/bootstrap-%23563D7C.svg?style=for-the-badge&logo=bootstrap&logoColor=white"/> <img id="techstack" alt="CSS3" src="https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white"/> <img id="techstack" alt="Django" src="https://img.shields.io/badge/django-%23092E20.svg?style=for-the-badge&logo=django&logoColor=white"/>
    <br>
    <img id="techstack" alt="Git" src="https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white"/> <img id="techstack" alt="GitHub" src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white"/> <img id="techstack" alt="Handsontable" src="https://img.shields.io/badge/Handsontable-%2343853D.svg?style=for-the-badge&logo=node-dot-js&logoColor=white"/> <img id="techstack" alt="HTML5" src="https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white"/>
    <br>
    <img id="techstack" alt="JavaScript" src="https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E"/> <img id="techstack" alt="Nginx" src="https://img.shields.io/badge/nginx-%23009639.svg?style=for-the-badge&logo=nginx&logoColor=white"/> <img id="techstack" alt="Python" src="https://img.shields.io/badge/python-%2314354C.svg?style=for-the-badge&logo=python&logoColor=white"/> <img id="techstack" alt="SQLite" src ="https://img.shields.io/badge/sqlite-%2307405e.svg?style=for-the-badge&logo=sqlite&logoColor=white"/></p>
</div>
{% include "footer.html" %}
</body>
</html>

templates/main/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB</title>
</head>

<body>
{% include "navbar.html" %}
<div id ="main-contents">
    <center><img src="https://github.com/ChanToRe/RCDB/blob/master/img/Main.png?raw=true"><br><br></center>
    <br>
    <h2>RCDB는 PC 사용자를 대상으로 제작되었습니다.</h2>
    <br>
    <p>&#10145; RCDB가 무엇인지 궁금하다면, <a href="http://rcdb.kr/info">Info</a>를 클릭하세요.</p>
    <p>&#10145; RCDB의 공지를 확인하고 싶다면, <a href="http://rcdb.kr/notice">Notice</a>를 클릭하세요.</p>
    <p>&#10145; RCDB를 사용하고 싶다면, <a href="http://rcdb.kr/rcdb">RCDB</a>를 클릭하세요.</p>
</div>
{% include "footer.html" %}
</body>
</html>

templates/navbar.html
<nav id="nav" class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'main:index' %}"><img src="https://github.com/ChanToRe/RCDB/blob/master/img/Logo.png?raw=true"></a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0 justify-content-end bg-light" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'info:index' %}">Info</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'notice:index' %}">Notice</a>
            </li>
            <li class="nav-item"></li>
                <a class="nav-link" href="{% url 'rcdb:index' %}">RCDB</a>
            </li>
        </ul>
    </div>
</nav>

templates/notice/notice_detail.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB</title>
</head>

<body>
{% include "navbar.html" %}
{% load md_filter %}
<div id="notice-detail" class="container my-3">
    <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ notice.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ notice.create_date }}
                </div>
            </div>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/notice/notice_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB</title>
</head>

<body>
{% include "navbar.html" %}
{% load md_filter %}

<div id="notice-list" class="container my-3">
    <h1 id="notice-notice">Notice</h1>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>No</th>
            <th>Title</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% if notice_list %}
        {% for notice in notice_list %}
        <tr>
            <td>{{ notice_list.paginator.count|sub:notice_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td>
                <a href="{% url 'notice:detail' notice.id %}">{{ notice.subject }}</a>
            </td>
            <td>{{ notice.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">공지가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        {% if notice_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ notice_list.previous_page_number }}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
        </li>
        {% endif %}

        {% for page_number in notice_list.paginator.page_range %}
        {% if page_number >= notice_list.number|add:-5 and page_number <= notice_list.number|add:5 %}
        {% if page_number == notice_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}

        {% if notice_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ notice_list.next_page_number }}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>

</div>
{% include "footer.html" %}
</body>
</html>

templates/rcdb/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon" href="/static/favicon.ico"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/handsontable@9.0.1/dist/handsontable.full.min.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" href="/static/style.css" type="text/css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/handsontable@9.0.1/dist/handsontable.full.min.js"></script>
    <script src="/static/jquery-3.6.0.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <title>RCDB</title>
</head>

<body>
{% include "navbar.html" %}
{% load md_filter %}
<div id="title">
    <h1>RCDB</h1>
</div>
<div id="export-buttons" class="visible">
    <button id="export-csv" class="btn size-medium bg-blue text-black shadow hover-moveup">
        Export csv file
    </button>
</div>
<div id="rcdb-notice">
    *시료의 무게가 미기재일 경우 Weight_g는 0으로 표기됩니다.<br>
    *시료의 종류가 미기재일 경우 Material은 NULL로 표기됩니다.<br>
    *LabID가 미기재일 경우 LabID는 NULL로 표기됩니다.
</div>
<div id="Handsontable">
    <script>
        let getList = [];
        let rabelList = ['id', 'Name','State','City', 'Site', 'Material', 'Weight_g', 'Laboratory', 'LabID', 'Age_BP', 'Error', 'Report' ];
        var rcdbs = JSON.parse("{{rcdbsJson|escapejs}}");
        for (let i =0; i<rcdbs.length;i++){
            getList.push([
                rcdbs[i].id,
                rcdbs[i].Name,
                rcdbs[i].State,
                rcdbs[i].City,
                rcdbs[i].Site,
                rcdbs[i].Material,
                rcdbs[i].Weight_g,
                rcdbs[i].Laboratory,
                rcdbs[i].LabID,
                rcdbs[i].Age_BP,
                rcdbs[i].Error,
                rcdbs[i].Report
            ])
        }

        var container = document.getElementById('Handsontable');
        document.getElementById("Handsontable").style.fontSize = '9pt';
        var hot = new Handsontable(container, {
            data: getList,
            rowHeaders: true,
            colHeaders: true,
            filters: true,
            dropdownMenu: true,
            licenseKey: 'non-commercial-and-evaluation',
            colHeaders: rabelList

        });
        document.getElementById("export-csv").addEventListener("click", function() {
            hot.getPlugin("exportFile").downloadFile("csv", {filename: "rcdb", columnHeaders: true});

        })
    </script>
</div>
<div id="UpDown-button">
    <a style="display:scroll;position:fixed;bottom:65px;right:5px;z-index: 2;opacity:0.3" href="#" title=Top><img src="https://github.com/ChanToRe/RCDB/blob/master/img/Up.png?raw=true" border="0"/></a>
    <a style="display:scroll;position:fixed;bottom:10px;right:5px;z-index: 2;opacity:0.3" href="#Down" title=Bottom><img src="https://github.com/ChanToRe/RCDB/blob/master/img/Down.png?raw=true" border="0"/></a>
</div>
{% include 'footer.html' %}
<div id="Down"></div>
</body>
</html>

templates/rcdb/notice_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ notice.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ notice.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ notice.create_date }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}